title: TallCat
theme: jekyll-theme-minimal
description: Webpage of the TallCat Applied Category Theory group at TalTech.
logo: images/tallcats.png
show_downloads: false
author:
  avatar: images/tallcats.png
sidebar:
  - title: "TallCat"
    image: images/tallcats.png



